# Custom Language File for Launcher Customizer

[ejs.app]
title = "HaluLNCH"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/HaluLNCH"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/HaluLNCH"
supportLink = "https://github.com/mchlauncher/HaluLNCH/issues"

[ejs.welcome]
welcomeHeader = "HaluLNCH"
welcomeDescription = "1 줄.<br>2 줄.<br>3 줄."
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."